name: blind_keyboard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  kdtree: ^0.2.0
  csv: ^5.0.1
  text_to_speech: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/Lang/he/he.json
    - assets/Lang/en/en.json
    - assets/Lang/he/words/words_2.json
    - assets/Lang/he/words/words_3.json
    - assets/Lang/he/words/words_4.json
    - assets/Lang/he/words/words_5.json
    - assets/Lang/he/words/words_6.json
    - assets/Lang/he/words/words_7.json
    - assets/Lang/he/words/words_8.json
    - assets/Lang/he/words/words_9.json
    - assets/Lang/he/words/words_10.json
    - assets/Lang/he/words/words_11.json
    - assets/Lang/he/words/words_12.json
    - assets/Lang/he/words/words_13.json
    - assets/Lang/he/words/words_14.json
    - assets/Lang/he/words/words_15.json
    - assets/Lang/he/words/words_16.json
    - assets/Lang/he/words/words_17.json
    - assets/Lang/he/words/words_18.json
    - assets/Lang/he/prefixes/words_1.json
    - assets/Lang/he/prefixes/words_2.json
    - assets/Lang/he/prefixes/words_3.json
    - assets/Lang/he/prefixes/words_4.json
    - assets/Lang/he/prefixes/words_5.json
    - assets/Lang/he/prefixes/words_6.json
    - assets/Lang/he/prefixes/words_7.json
    - assets/Lang/he/prefixes/words_8.json
    - assets/Lang/en/words/words_1.json
    - assets/Lang/en/words/words_2.json
    - assets/Lang/en/words/words_3.json
    - assets/Lang/en/words/words_4.json
    - assets/Lang/en/words/words_5.json
    - assets/Lang/en/words/words_6.json
    - assets/Lang/en/words/words_7.json
    - assets/Lang/en/words/words_8.json
    - assets/Lang/en/words/words_9.json
    - assets/Lang/en/words/words_10.json
    - assets/Lang/en/words/words_11.json
    - assets/Lang/en/words/words_12.json
    - assets/Lang/en/words/words_13.json
    - assets/Lang/en/words/words_14.json
    - assets/Lang/en/words/words_15.json
    - assets/Lang/en/words/words_16.json
    - assets/Lang/en/words/words_17.json
    - assets/Lang/en/words/words_18.json
    - assets/Lang/he/words/tree_2.json
    - assets/Lang/he/words/tree_3.json
    - assets/Lang/he/words/tree_4.json
    - assets/Lang/he/words/tree_5.json
    - assets/Lang/he/words/tree_6.json
    - assets/Lang/he/words/tree_7.json
    - assets/Lang/he/words/tree_8.json
    - assets/Lang/he/words/tree_9.json
    - assets/Lang/he/words/tree_10.json
    - assets/Lang/he/words/tree_11.json
    - assets/Lang/he/words/tree_12.json
    - assets/Lang/he/words/tree_13.json
    - assets/Lang/he/words/tree_14.json
    - assets/Lang/he/words/tree_15.json
    - assets/Lang/he/words/tree_16.json
    - assets/Lang/he/words/tree_17.json
    - assets/Lang/he/words/tree_18.json
    - assets/Lang/he/prefixes/tree_1.json
    - assets/Lang/he/prefixes/tree_2.json
    - assets/Lang/he/prefixes/tree_3.json
    - assets/Lang/he/prefixes/tree_4.json
    - assets/Lang/he/prefixes/tree_5.json
    - assets/Lang/he/prefixes/tree_6.json
    - assets/Lang/he/prefixes/tree_7.json
    - assets/Lang/he/prefixes/tree_8.json
    - assets/Lang/en/words/tree_1.json
    - assets/Lang/en/words/tree_2.json
    - assets/Lang/en/words/tree_3.json
    - assets/Lang/en/words/tree_4.json
    - assets/Lang/en/words/tree_5.json
    - assets/Lang/en/words/tree_6.json
    - assets/Lang/en/words/tree_7.json
    - assets/Lang/en/words/tree_8.json
    - assets/Lang/en/words/tree_9.json
    - assets/Lang/en/words/tree_10.json
    - assets/Lang/en/words/tree_11.json
    - assets/Lang/en/words/tree_12.json
    - assets/Lang/en/words/tree_13.json
    - assets/Lang/en/words/tree_14.json
    - assets/Lang/en/words/tree_15.json
    - assets/Lang/en/words/tree_16.json
    - assets/Lang/en/words/tree_17.json
    - assets/Lang/en/words/tree_18.json





  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
